name: resshift
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - certifi=2023.11.17=py310h06a4308_0
  - cffi=1.16.0=py310h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.7=py310hdda0065_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - numpy=1.26.3=py310h5f9d8c6_0
  - numpy-base=1.26.3=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.12=h7f8727e_0
  - pillow=10.0.1=py310ha6cbd5a_0
  - pip=23.3.1=py310h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_0
  - setuptools=68.2.2=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.1.0=py310_cu118
  - torchtriton=2.1.0=py310
  - torchvision=0.16.0=py310_cu118
  - typing_extensions=4.7.1=py310h06a4308_0
  - urllib3=1.26.18=py310h06a4308_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==2.0.0
    - addict==2.4.0
    - albumentations==1.3.1
    - antlr4-python3-runtime==4.9.3
    - asttokens==2.4.1
    - cachetools==5.3.2
    - contourpy==1.2.0
    - cycler==0.12.1
    - decorator==5.1.1
    - einops==0.7.0
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - facexlib==0.3.0
    - filterpy==1.4.5
    - fonttools==4.47.0
    - fsspec==2023.12.2
    - ftfy==6.1.3
    - future==0.18.3
    - google-auth==2.26.1
    - google-auth-oauthlib==1.2.0
    - grpcio==1.60.0
    - huggingface-hub==0.20.2
    - imageio==2.33.1
    - imgaug==0.4.0
    - importlib-metadata==7.0.1
    - ipdb==0.13.13
    - ipython==8.19.0
    - jedi==0.19.1
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - llvmlite==0.41.1
    - lmdb==1.4.1
    - loguru==0.7.2
    - lpips==0.1.4
    - markdown==3.5.1
    - matplotlib==3.8.2
    - matplotlib-inline==0.1.6
    - numba==0.58.1
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - openai-clip==1.0.1
    - opencv-python==4.8.0.74
    - opencv-python-headless==4.9.0.80
    - packaging==23.2
    - pandas==2.1.4
    - parso==0.8.3
    - pexpect==4.9.0
    - platformdirs==4.1.0
    - prompt-toolkit==3.0.43
    - protobuf==4.23.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pygments==2.17.2
    - pyiqa==0.1.10
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - qudida==0.0.4
    - regex==2023.12.25
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - safetensors==0.4.1
    - scikit-image==0.22.0
    - scikit-learn==1.3.2
    - scipy==1.11.4
    - shapely==2.0.2
    - six==1.16.0
    - stack-data==0.6.3
    - tensorboard==2.15.1
    - tensorboard-data-server==0.7.2
    - threadpoolctl==3.2.0
    - tifffile==2023.12.9
    - timm==0.9.12
    - tomli==2.0.1
    - torch==2.1.2+cu118
    - tqdm==4.66.1
    - traitlets==5.14.1
    - tzdata==2023.4
    - wcwidth==0.2.13
    - werkzeug==3.0.1
    - xformers==0.0.23.post1+cu118
    - yapf==0.40.2
    - zipp==3.17.0
